services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - ./SQL Database/init.sql:/docker-entrypoint-initdb.d/0.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_USER: admin
      MYSQL_PASSWORD: 09022005      
      MYSQL_ROOT_PASSWORD: 09022005
    networks:
      - restaurantnet

  backend:
    build:
      context: Backend
      dockerfile: ./Dockerfile
    image: backend
    environment:
      NODE_ENV: staging
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mysql
    networks:
      - restaurantnet

  frontend:
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    image: frontend
    environment:
      NODE_ENV: staging
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - restaurantnet

networks:
  restaurantnet:
    driver: bridge
